name: cd

on:
  workflow_run:
    workflows: ["ci"]
    branches: [master]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
 build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Authenticate to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ECR_URL }}
    
      - name: Perform a Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.AWS_ECR_URL }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }}